gantt
    dateFormat YYYY-MM-DD
    title Y project

    Deadline proj :deadl1, 2025-09-15, 0d

    section Progettazione
        scrivi requisiti    :a1, 2025-09-10, 4d
        riempi form         :a2, after a1, until deadl1
        
    section Implementazione
        crea logo           :b1, after deadl1, 1d
        